### ISSUE TITLE
Conversion between FlagBit and FlagMask variants

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#10]
I'm not really clear on the intended distinction between these, but I have a function like this that won't typecheck:
```hs
getMaxUsableSampleCount :: MonadIO io => VkPhysicalDevice -> io VkSampleCountFlagBits
getMaxUsableSampleCount physicalDevice = do
  limits <- getField @"limits" <$> getPhysicalDeviceProperties physicalDevice
  let sampleCounts = min (getField @"framebufferColorSampleCounts" limits) (getField @"framebufferDepthSampleCounts" limits)
  return $
    fromMaybe VK_SAMPLE_COUNT_1_BIT .
    find ((0 /=) . (sampleCounts .&.)) $
    [
      VK_SAMPLE_COUNT_64_BIT,
      VK_SAMPLE_COUNT_32_BIT,
      VK_SAMPLE_COUNT_16_BIT,
      VK_SAMPLE_COUNT_8_BIT,
      VK_SAMPLE_COUNT_4_BIT,
      VK_SAMPLE_COUNT_2_BIT
    ]
```

The type works if I replace the return type with `VkSampleCountFlags`.  However, I need FlagBits because that's what's consumed later by the `samples` field of the `VkImageCreateInfo` structure.  Only way I can see to work around this is something like:

```hs
getMaxUsableSampleCount :: MonadIO io => VkPhysicalDevice -> io VkSampleCountFlagBits
getMaxUsableSampleCount physicalDevice = do
  limits <- getField @"limits" <$> getPhysicalDeviceProperties physicalDevice
  let sampleCounts = min (getField @"framebufferColorSampleCounts" limits) (getField @"framebufferDepthSampleCounts" limits)
  return $
    fromMaybe VK_SAMPLE_COUNT_1_BIT .
    fmap snd .
    find ((0 /=) . (sampleCounts .&.) . fst) $
    [
      (VK_SAMPLE_COUNT_64_BIT, VK_SAMPLE_COUNT_64_BIT),
      (VK_SAMPLE_COUNT_32_BIT, VK_SAMPLE_COUNT_32_BIT),
      (VK_SAMPLE_COUNT_16_BIT, VK_SAMPLE_COUNT_16_BIT),
      (VK_SAMPLE_COUNT_8_BIT, VK_SAMPLE_COUNT_8_BIT),
      (VK_SAMPLE_COUNT_4_BIT, VK_SAMPLE_COUNT_4_BIT),
      (VK_SAMPLE_COUNT_2_BIT, VK_SAMPLE_COUNT_2_BIT)
    ]
```

**Comment by achirkin** [comment]
There was a discussion regarding this somewhere in the Vulkan spec repository. The point of having two types is that `**FlagBit` is always supposed to be a single bit and `**FlagMask` can have multiple bits enabled. In the discussion it seemed to be important do distinguish these two, especially when it comes to which arguments a Vulkan function accepts.

I decided to enforce this distinction on the type level in haskell. What is important, there is a real type `VkSampleCountBitmask a`, and two type aliases:
```Haskell
type VkSampleCountFlags = VkSampleCountBitmask FlagMask
type VkSampleCountFlagBits = VkSampleCountBitmask FlagBit
```
The `FlagMask` type has more instances, such as `Num` and `Bits`, but `FlagBit` does not.
The type parameter `a` here is phantom, so you can manipulate `FlagMask` and then coerce it to `FlagBit`.
You can use a function `coerce` from module `Data.Coerce` for this.

That being said, I think you have a good point here.
We can add two convenience functions `bitToMask` and `maskToBit`:
```
bitToMask = coerce

#ifndef UNSAFE_MASKTOBIT
maskToBit = coerce
#else
maskToBit = ... check if mask has a single bit enabled and coerce ...
#endif
```
The problem is that it may require a typeclass to make this function polymorphic, which means a lot more of generated code to an already big project, which means even slower compilation and haddocks...

**Comment by Rotaerk** [comment]
Thinking on it, I can't think of a reason off-hand that we would need to convert from **FlagMask to **FlagBit.  Maybe we don't need a `maskToBit` function at all, and only a `bitToMask`.  If that were the case, then I could just modify my original function such that:
```hs
find ((0 /=) . (sampleCounts .&.))
```
becomes:
```hs
find ((0 /=) . (sampleCounts .&.) . bitToMask)
```
Though, maybe some situation would come up where such a conversion would be useful.  Or maybe it would be better to make a `maskBits :: x FlagMask -> [x FlagBit]` function instead?

**Comment by achirkin** [comment]
Yes, `bitToMask` and `maskToBits` in your variant sound like a  good pair of helper functions.
I remember I had to write a loop over bits of a mask somewhere, `maskToBits` would simplify that a lot.

**Comment by achirkin** [comment]
Finally managed to add these functions :)

**Comment by Rotaerk** [comment]
Nice!  Thanks.
