### ISSUE TITLE
MoltenVK on High Sierra: GLFW reports that vulkan is not supported!

### ISSUE THREAD

**Issue by o1lo01ol1o** [achirkin/vulkan#20]
The readme states that `vulkan-api` was tested on MoltenVK.  How was GLFW linked to vulkan?  It looks like `GLFW-b` packages a version of glfw the potentially predates MoltenVK support. I'm abled to install glfw (via source) and am told that I finds the vulkan libraries.  However, it looks like `stack build` in vulkan-examples links the wrong `glfw`: 

```
stack exec ve-06-Drawing
GLFW version: 3.2.1 Cocoa NSGL chdir menubar retina
Terminated GLFW.
ve-06-Drawing: VulkanException {vkeCode = Nothing, vkeMessage = "GLFW reports that vulkan is not supported!"}

```

**Comment by o1lo01ol1o** [comment]
Ok, I now see that https://github.com/bsl/bindings-GLFW/pull/58 and your work on MoltenVK support predates the most recent hackage upload, so that much is answered.  I've added the moltenVK `lib` and `include` directories to the extra-lib-dirs and extra-include-dirs in the `stack.yaml`, but still not dice.

**Comment by achirkin** [comment]
GLFW supports MoltenVK since version 3.3. I wanted to update `bindings-GLFW` to this version, but did not come to actually doing it, because my primary machine is linux.
At the same time, `vulkan-api` worked for me with MoltenVK - windowless. So, if you want to get triangles on a screen of Mac OS, you need to start with [bindings-GLFW/Upgrade-3.3](https://github.com/bsl/bindings-GLFW/tree/Upgrade-3.3). You can also try to create a window handle using GLFW without asking for Vulkan, then manually query for required Mac OS window extensions.

**Comment by o1lo01ol1o** [comment]
So `bindings-GLFW` does not yet support MoltenVK and this would need to implemented in the `Upgrade-3.3` branch.  The alternate, untested, approach would be to use GLFW without vulkan support and handle the vulkan-GLFW some other way.  Is this correct?

**Comment by achirkin** [comment]
Yep, this is correct. Personally, I think the first option is easier :)

**Comment by o1lo01ol1o** [comment]
Is there a guide to the first option?  :)

**Comment by achirkin** [comment]
In general, you just replace the content of `bindings-GLFW/glfw/` folder with the release 3.3 GLFW source code, and then carefully add new bindings to `bindings-GLFW/Bindings/GLFW.hsc`.The latter is pretty intuitive, just follow the logic of the previously defined functions :)
Afterwards, you would need to update higher-level bindings via `GLFW-b/util/genC.hs`.

**Comment by o1lo01ol1o** [comment]
Thanks for the overview, I'll give it a shot.
