### ISSUE TITLE
Undefined reference to 'vkCreateDebugReportCallbackEXT'

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#3]
I'm working through https://vulkan-tutorial.com/, and translating the example code to Haskell as I go.  My source is here:  https://github.com/rotaerk/vulkanTest.

I got as far as adding validation layers, with everything building and running as expected, but when I added the debug callback (https://github.com/Rotaerk/vulkanTest/blob/master/src/Main.hs#L184), I got the following link error:

> Linking dist/build/vulkanTest/vulkanTest ...
> dist/build/vulkanTest/vulkanTest-tmp/Main.p_o: In function `sGDa_info':
> /tmp/nix-build-vulkanTest-0.1.0.0.drv-0/ghc15641_0/ghc_9.p_o:(.text.sGDa_info+0x87): undefined reference to `vkDestroyDebugReportCallbackEXT'
> dist/build/vulkanTest/vulkanTest-tmp/Main.p_o: In function `cIyh_info':
> /tmp/nix-build-vulkanTest-0.1.0.0.drv-0/ghc15641_0/ghc_9.p_o:(.text.sGCM_info+0x2cf): undefined reference to `vkCreateDebugReportCallbackEXT'
> collect2: error: ld returned 1 exit status
> `cc' failed in phase `Linker'. (Exit code: 1)

I'm not sure whether there's a problem with what I'm doing, so this may not be an issue with your bindings.  However, I ran across this [stackoverflow post](https://stackoverflow.com/questions/37900051/vkcreatedebugreportcallback-ext-not-linking-but-every-other-functions-in-vulkan) indicating that for functions from Vulkan extensions, you're supposed to use vkGetInstanceProcAddr to dynamically load them.  I was told that this is true for _all_ extensions.

Your bindings don't do that; instead they do a foreign import of them just like with the core Vulkan functions.  I do see that you have some examples using extensions, and I'm not sure how those would work if the above is true ...

Do you have any idea where the problem lies, here?

**Comment by Rotaerk** [comment]
I got my code to link and run as intended by following the suggestion of that stackoverflow post.  See this diff:  https://github.com/Rotaerk/vulkanTest/commit/e923185fb710b6ce30b2dddd9ee1ca7d75ab2a1a#diff-f8f3412da88cd4806f23d59fe59ebc3b

I suspect that the way your bindings are generated for extensions will need to be changed to work similar to what I wrote (which is based on the vulkan tutorial).  However, I wonder if there's a way to structure it so that vkGetInstanceProcAddr is only called the first time you need that extension procedure, rather than _every time you call it_.  Though it might not be worth keeping those functions sitting around when not being used.

As for how it might work on _your_ machine, I'm guessing that directly linking extension procedures, rather than going through vkGetInstanceProcAddr, might _sometimes_ work, but that it's unreliable and platform-specific.

**Comment by achirkin** [comment]
Ah, yes, I see! You are totally right. I was relying on `vulkan.h` or `vulkan_core.h` having these function definitions. I guess, depending on the vendor and platform, some extension functions are available in the `.lib` stub and some are not.

What I could do in this situation is to generate another version for each function from extensions that would use `vkGetInstanceProcAddr` just like you did in your program. To address your every-time-you-call-it problem, we could make something like this:
```Haskell
destroyDebugReportCallbackDyn
    :: VkInstance
    -> Maybe (VkDebugReportCallbackEXT -> Ptr VkAllocationCallbacks -> IO ())
destroyDebugReportCallbackDyn vkInstance = unsafePerformIO $ do
  procPtr <- castFunPtr <$> vkGetInstanceProcAddr vkInstance (Ptr "destroyDebugReportCallbackEXT"#)
  return $
    if procPtr /= nullFunPtr
    then
      Just $ mkDestroyDebugReportCallbackEXT procPtr vkInstance
    else
      Nothing
{-# NOINLINE destroyDebugReportCallbackDyn #-}
```
Do you think this is usable enough?

Also, could you please try to build & run `vulkan-examples` and `vulkan-triangles`? In these programs, I also followed the vulkan-tutorial, but I skipped the debug report callbacks part, because luckily the validation layers provided good default console callbacks. A few functions to set up a swapchain come from vulkan extensions too and I wonder if they are linked on other systems correctly.

**Comment by achirkin** [comment]
Keeping in mind [`vkGetInstanceProcAddr`](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetInstanceProcAddr.html) documentation I should generate:
 * a dynamically loaded variant of a function using `vkGetInstanceProcAddr`
 * `CString` name pattern for each function
 * `PFN_xx` and `HS_xx` type aliases
 *  Maybe even type-level symbol alias?..

Also maybe I should delete plain foreign imported functions from `EXT.**` modules.

**Comment by Rotaerk** [comment]
Yeah, I think the way you've implemented it makes sense, returning a Maybe containing the actual function.  Though, I don't really have any experience with unsafePerformIO, and I'm not sure how I feel about it being used in that context.  Is it really always going to produce the same output for a given VkInstance?  I'll let you decide whether that makes sense.

I do think you should delete the existing foreign imports for extensions, since they are unreliable and may only mislead people.

I'll try getting your examples to build, and see if I run into similar linker errors.

**Comment by Rotaerk** [comment]
Also, I'm not sure {function name}Dyn makes much sense with that signature, because it's not a dynamic version of the function itself, but something that requests the function from vulkan, which the user would then bind to {function name} or whatever. To me it makes more sense to have a "get", "load", "req(uest)", etc. prefix instead.

Or maybe uh ...  

> requestExt @HS_vkCreateDebugReportCallbackEXT

or something?

**Comment by Rotaerk** [comment]
Well, I just tried building vulkan-examples, locally, and it works if I comment-out examples 5 and 6 from the cabal file.  If either of those is included, it fails to build, with this error:

> &lt;command line&gt;: can't load .so/.DLL for: /nix/store/w509n1jih1zw98m0fr221wzar2dl3pn6-vulkan-api-1.1.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.0.0-F6qZMLWf42L7B8iyToEeP8-ghc8.2.2.so (/nix/store/w509n1jih1zw98m0fr221wzar2dl3pn6-vulkan-api-1.1.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.0.0-F6qZMLWf42L7B8iyToEeP8-ghc8.2.2.so: undefined symbol: vkDestroyDebugReportCallbackEXT)

I'm not exactly sure _why_ that is the error, though, since you're not calling that anywhere in your examples' code...  It also seems like an odd coincidence that it's complaining about one of the very extension functions that I've been trying to use in my own code; makes me wonder if there's some weird Nix-related shenanigans going on.  (Because aside from resolving common dependencies through the same builds in the Nix store, there shouldn't be any cross-contamination ...)

**Comment by achirkin** [comment]
How about these:
[`vkGetInstanceProc @VkDestroySurfaceKHR vkInstance :: IO HS_vkDestroySurfaceKHR`](https://github.com/achirkin/vulkan/blob/master/vulkan-examples/Lib/Vulkan/Presentation.hs#L38-L42) and
[`vkGetInstanceProc @VkCreateInstance VK_NULL :: IO HS_vkCreateInstance`](https://github.com/achirkin/vulkan/blob/master/vulkan-examples/01-CreateInstance.hs#L59-L60)?

Since I am trying here to keep the bindings low-level, I can just provide several helpers and let users decide how to manage obtained function pointers. That is, for every function `vkXxx`, I generate:
  * `type VkXxx = "vkXxx"` -- type-level symbol to use with `TypeApplications`
  * `pattern VkXxx :: CString` -- C name of a function so that a user does not need to manage memory for it.
  * `type PFN_vkXxx` and `type HS_vkXxx` similar to @Functpointers@ module
  * [`instance VulkanInstanceProc "vkXxx"`](https://github.com/achirkin/vulkan/blob/master/vulkan-api/src/Graphics/Vulkan/Marshal/InstanceProc.hs) for using `vkGetInstanceProc` as a simpler alternative to `vkGetInstanceProcAddr`.

I have not deleted plain foreign import versions yet, because ATM it is not clear which functions are guaranteed to be present in the vulkan loader library.


PS: did you try [`vulkan-triangles`](https://github.com/achirkin/vulkan/tree/master/vulkan-triangles) program?

**Comment by Rotaerk** [comment]
Well, wouldn't the result have to be an IO (Maybe HS_vkDestroySurfaceKHR), or are you making it throw on failure?  Aside from that, I think that makes sense.

And yea, [the spec for vkGetInstanceProcAddr](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetInstanceProcAddr.html) says: 

> Vulkan commands are not necessarily exposed statically on a platform. Function pointers for all Vulkan commands can be obtained with [vkGetInstanceProcAddr].

I find that a little vague...  Is it saying that _any_ Vulkan function is potentially not exposed statically, or only some of them?  Does it only apply to functions from extensions, or perhaps a subset of functions from extensions?  And if there are functions that are guaranteed to be statically exposed, which ones are they?  I would think that _at the very least_ vkGetInstanceProcAddr and vkCreateInstance should always be statically exposed.

PS: No, I haven't tried building vulkan-triangles yet.  I'll try that tomorrow (won't have time tonight).

**Comment by Rotaerk** [comment]
Actually, it looks like there's a distinction between "instance functions" and "device functions", per [this page](https://vulkan.lunarg.com/doc/view/1.1.70.1/windows/loader_and_layer_interface.html#user-content-instance-versus-device).  And for device functions, there's another function analogous to vkGetInstanceProcAddr that you're supposed to use, called vkGetDeviceProcAddr.  Might need to add an analogous helper for that too...

That page also talks about statically/dynamically linking directly to the loader versus indirectly linking through these vkGet*ProcAddr functions, further down.  It also says this:

> The loader library on Windows, Linux and Android will export all core Vulkan and all appropriate Window System Interface (WSI) extensions.

So I think what this means is that, even if the Vulkan spec itself leaves open the possibility that _any_ function might have to be obtained through a vkGet*ProcAddr function, the specific implementation that the LunarG loader provides guarantees that all core functions and all "appropriate" WSI extension functions are directly linkable.  However, it's unclear what "appropriate WSI extensions" includes...

**Comment by Rotaerk** [comment]
The "appropriate WSI extensions", I think, are the ones mentioned [here](https://vulkan.lunarg.com/doc/view/1.1.70.1/windows/loader_and_layer_interface.html#user-content-wsi-extensions).

Anyway, since your bindings shouldn't be tied to any specific platform, and could theoretically work on something that's _not_ Windows, Linux, or Android, it probably _is_ appropriate to leave all the direct bindings in there, even for the functions that are pretty much guaranteed _not_ to be exposed on those three platforms.  But it might be worth mentioning in your documentation that most of them are likely unusable on most platforms.

**Comment by acowley** [comment]
Hi @achirkin, I was lurking on this issue since @Rotaerk mentiond the errors he hit on IRC, and I'd seen very similar things but gave up because I figured the problem was on my end. We're both using `nix`, so something may be different there. For what it's worth, I can not build the `vulkan-triangles` program. I get, 

~~```
Building library for vulkan-triangles-0.1.0.0..
[11 of 11] Compiling Lib              ( src/Lib.hs, /home/acowley/src/vulkan-haskell/vulkan-triangles/dist-newstyle/build/x86_64-linux/ghc-8.2.2/vulkan-triangles-0.1.0.0/build/Lib.o )
<command line>: can't load .so/.DLL for: /nix/store/y84nl8fis3hwgn0ga3lqlcnkyymd4ijz-vulkan-api-0.2.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-0.2.0.0-BmK1VBt2JeBGp5VRKXfXlY-ghc8.2.2.so (/nix/store/y84nl8fis3hwgn0ga3lqlcnkyymd4ijz-vulkan-api-0.2.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-0.2.0.0-BmK1VBt2JeBGp5VRKXfXlY-ghc8.2.2.so: undefined symbol: vkGetImageSparseMemoryRequirements2KHR)
cabal: Failed to build vulkan-triangles-0.1.0.0 (which is required by
exe:vulkan-triangles from vulkan-triangles-0.1.0.0).
```~~ (Sorry, that was with my existing checkout. I bumped to the latest `vulkan`, `GLFW-b`, and `bindings-GLFW`). The error is,

```
[11 of 11] Compiling Lib              ( src/Lib.hs, /home/acowley/src/vulkan-haskell/vulkan-triangles/dist-newstyle/build/x86_64-linux/ghc-8.2.2/vulkan-triangles-0.1.0.0/build/Lib.o )
<command line>: can't load .so/.DLL for: /nix/store/z0vngwnsnhammalf7438bfxq98my4lvx-vulkan-api-0.2.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.1.0-LosBtyrLcBAHZRNZm7eJ4F-ghc8.2.2.so (/nix/store/z0vngwnsnhammalf7438bfxq98my4lvx-vulkan-api-0.2.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.1.0-LosBtyrLcBAHZRNZm7eJ4F-ghc8.2.2.so: undefined symbol: vkDestroyDebugReportCallbackEXT)
cabal: Failed to build vulkan-triangles-0.1.0.0 (which is required by
exe:vulkan-triangles from vulkan-triangles-0.1.0.0).
```
I can run various other vulkan things on this machine, so I know it's not totally broken.

**Comment by achirkin** [comment]
Thank you guys for the hints! To me it feels like nix governs linking process slightly differently compared to stack.
I think it is time for me to learn nix :) I will try to set it up and investigate the problem next week.

**Comment by achirkin** [comment]
@Rotaerk , I've just added two pairs of helpers [`vk[Get|Lookup][Device|Instance]Proc`](https://github.com/achirkin/vulkan/blob/master/vulkan-api/src/Graphics/Vulkan/Marshal/Proc.hs).

**Comment by Rotaerk** [comment]
Awesome, that works perfectly:  https://github.com/Rotaerk/vulkanTest/commit/9815c75d879319643a6b01758edff0c421e0d7f6.

And I do like the choice to omit the null-checking of the result, by using Get rather than Lookup, while retaining the option to play it safe.  As I understand it, it should *never* fail if you've already confirmed support for the extension up-front.

As far as I'm concerned, this issue can be closed. :)

**Comment by Rotaerk** [comment]
I should mention that vulkan-examples still doesn't build for me, though.  Still says:

\<command line\>: can't load .so/.DLL for: /nix/store/ld5lvfjc8i53zibick3sfxsb7krbms9b-vulkan-api-1.1.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.1.0-LosBtyrLcBAHZRNZm7eJ4F-ghc8.2.2.so (/nix/store/ld5lvfjc8i53zibick3sfxsb7krbms9b-vulkan-api-1.1.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.1.0-LosBtyrLcBAHZRNZm7eJ4F-ghc8.2.2.so: undefined symbol: vkDestroyDebugReportCallbackEXT)

**Comment by Rotaerk** [comment]
I just noticed something else that doesn't work for some reason:  When I am in my nix-shell for my own project, if I run 'cabal repl', I get the same 'undefined symbol' error as above, even though I'm not calling vkDestroyDebugReportCallbackEXT directly anymore.  Odd thing is that if I simply run 'ghci', I can then 'import Graphics.Vulkan.Ext' with no issue.

I wonder if, as long as you're depending on LunarG's vulkan loader, you should _not_ foreign import the extensions...  (Other than those WSI ones, of course.)  It seems like the mere presence of a foreign import of functions that aren't exposed by the vulkan loader is causing problems, at least in the context of nix.  (I really don't know enough about how all this works to begin to speculate as to why.)

**Comment by achirkin** [comment]
Yes, seems like nix by default passes different flags to ghc builds. 
I tried various options to compile `vulkan-triangles` and found that cabal flags `--disable-executable-dynamic` for `vulkan-triangles` and `--enable-split-sections` for `vulkan-api` always succeeds, because it ensures `vulkan-api` is linked statically to the executable and no unused (and non-available) functions are linked. On the other hand, configuring the program with `--enable-executable-dynamic` always fails.

At this moment, I added a white list of extensions that could be included into the vulkan loader library and removed FFI functions from all the rest of extensions. Unfortunately, linking still can fail if you use vulkan loader 1.0, because it does not have some functions from vulkan 1.1 that are already in `vulkan-api`. I will try to make cabal flags to disable newer feature sets, but it might be more difficult.

**Comment by Rotaerk** [comment]
Yea, the vulkan-loader currently available in nixpkgs is 1.0, so currently when I try to build vulkan-examples, I get:

> \<command line\>: can't load .so/.DLL for: /nix/store/p1lqidcsf2y9qsz0wfwdd869kcd5wkbr-vulkan-api-1.1.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.1.0-DZo5sQoNwHC4ndXaXP1txw-ghc8.2.2.so (/nix/store/p1lqidcsf2y9qsz0wfwdd869kcd5wkbr-vulkan-api-1.1.0.0/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHSvulkan-api-1.1.1.0-DZo5sQoNwHC4ndXaXP1txw-ghc8.2.2.so: undefined symbol: **vkAcquireNextImage2KHR**)

This function seems to be one that was introduced in 1.1.  I tried replicating your GHC flags by setting the 'enableSharedExecutables' attribute (in my default.nix file) to false when building vulkan-examples, and the 'enableDeadCodeElimination' attribute to true when building vulkan-api.  This didn't remove the error.  (You can see which GHC flags it's using for these attributes [here](https://github.com/NixOS/nixpkgs/blob/284756c76f7032684019ae42f44f7282d1e0309a/pkgs/development/haskell-modules/generic-builder.nix#L129-L156), if you can get through all the nix code around it.)

**Comment by achirkin** [comment]
@Rotaerk I added cabal flags to control for which versions of vulkan api you need native FFI calls. Setting a flag to false means replacing FFI calls with `vkGet***ProcAddr` where possible.
Could you please try it  with your configuration?

**Comment by Rotaerk** [comment]
@achirkin 

I pulled your changes, and my own vulkanTest project continued to build, but at run-time, vkCreateInstance failed until I rebuilt vulkan-api with the useNativeFFI-1-0 flag enabled.  (If it doesn't run at all with this flag disabled, is it ever valuable to disable it?)  Also, with useNativeFFI-1-1 disabled, I no longer get the error from 'cabal repl'; with it enabled, 'cabal repl' fails.

As for vulkan-examples, I was able to build it just fine, after installing glslangValidator.  But like my project, there were run-time errors until I enabled that flag.  Once I did, they all ran fine.  I finally saw the triangle from example 6. :)

And last but not least, I figured out what was triggering the "undefined symbol: vkAcquireNextImage2KHR" error when building vulkan-examples 5 and 6 (and probably vulkan-triangles).  It happens during the TH-driven compile-time call to compileGLSL.  Just installing glslangValidator does _not_ resolve this issue, because the error happens before it gets to the [findExecutable call](https://github.com/achirkin/vulkan/blob/f55335c4bf4bc32fc6abd8ac94a6bb8489366981/vulkan-examples/Lib/Utils/TH.hs#L40).  Since that's the very first thing compileGLSL is doing, the error must happen during whatever setup (dynamic linking?) is done to allow TH to call that function in the first place.  And this is what's broken by the existence of 1.1 foreign imports in vulkan-api, when the installed vulkan-loader is 1.0.

Does that understanding of the problem change anything, or are your cabal flags still the best option here?  I'm not really sure *why* GHC demands every foreign import be resolved when it's running template-haskell code, or *why* cabal repl demands the same (when it's *not* calling compileGLSL), but maybe there's a way to make them not do that?

**Comment by achirkin** [comment]
Great, since the original problem resolved, I can close the issue :)

Regarding the flags for features. You can disable FFI for all vulkan versions and this would result in no dependency on Vulkan loader at compile time at all (ATM except `vkGetDeviceProcAddr` and `vkGetInstanceProcAddr`)! But you still can locate all Vulkan symbols at runtime using lookup functions from `Graphics.Vulkan.Marshal.Proc`. Ideally, later I can adapt the lookup functions to link to `vkGetDeviceProcAddr` and `vkGetInstanceProcAddr` explicitly dynamically at runtime. As a result, turning off these flags would disable `extra-libraries` field in .cabal file and hackage would be able to generate haddocks for the package.
The takeway message is: `useNativeFFI-x-y` flags enable/disable `foreign import` calls only, and all of them can be disabled if needed (you just have to avoid using these functions directly and use the lookup functions instead).

Regarding the `undefined symbol: vkAcquireNextImage2KHR`. I really don't understand what is happening in your setup :) The [template haskell code](https://github.com/achirkin/vulkan/blob/master/vulkan-examples/Lib/Utils/TH.hs#L27) in the examples does not depend on `vulkan-api` at all! It just executes some program (`glslangValidator`) and copies its output into an `Addr#`. I believe that parts of the program get compiled with `-dynamic` flag (for either TH run or for ghci) which results in lookup of all defined FFI symbols during linking.

**Comment by Rotaerk** [comment]
vkCreateInstance should probably be one of the functions that is always imported, because you can't use vkGetInstanceProcAddr without already having an instance.

And you're right, I hadn't noticed that compileGLSL had no dependency on vulkan-api.  So I have no idea either...

Anyway, thanks for resolving this issue so quickly!

**Comment by achirkin** [comment]
@Rotaerk fyi, `vkCreateInstance` could be looked up too, with null pointer as argument. Check out this https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetInstanceProcAddr.html. So, `vkGetInstanceProcAddr` is the only function needed to bootstrap all others.

**Comment by Rotaerk** [comment]
Interesting; k.

**Comment by Rotaerk** [comment]
Actually, as I said in https://github.com/achirkin/vulkan/issues/3#issuecomment-380307875, I was seeing run-time failures in both my project and the examples until I enabled useNativeFFI-1-0.  However, you wrote it so that in the absence of that flag, all the functions are implemented in terms of vkGetInstanceProc, so I would expect it to work, albeit with the run-time overhead of dynamic function-lookup.  I agree that, in theory, you should be able to lookup vkCreateInstance using vkGetInstanceProcAddr, but in practice, I was seeing failures.  I wonder why...  Maybe another nixpkgs-specific quirk...

I'll test this a bit tonight, and see if I can get a better understanding of why.

**Comment by achirkin** [comment]
That's because some functions do not have `VkDevice` or `VkInstance` as arguments, so I have to implement them as `error msg`. I decided not to add new arguments to functions, because this would confuse users even more. That is: some functions are implemented via `VkDevice`, some functions are implemented via `VkInstance`, and some functions are implemented via `error`; all of these functions come with compile-time warnings attached if corresponding flags are not enabled.

**Comment by Rotaerk** [comment]
Ah, yeah that's it.  Makes sense.
