### ISSUE TITLE
VK_ERROR_INCOMPATIBLE_DRIVER error on nixos

### ISSUE THREAD

**Issue by locallycompact** [achirkin/vulkan#35]
I have a branch here that allows the examples to compile on nixos, but I get a VK_ERROR_INCOMPATIBLE_DRIVER when trying to run it. `vulkaninfo` by itself works fine and doesn't report a driver error, so raising this as an issue in case someone knows what's going on.

https://github.com/locallycompact/vulkan-1

**Comment by o1lo01ol1o** [comment]
Probably you'll need to patch the needed derivations to the runtime derivations.  I just did this on darwin here: #36

**Comment by Rotaerk** [comment]
@locallycompact, is this still an issue for you?

I don't use nix via stack.  I just use a shell.nix to setup my development environment, and then I build using cabal new-* commands.  However, when I upgraded NixOS a week or two ago, for the first time in 6 months or so, I started getting the VK_ERROR_INCOMPATIBLE_DRIVER error.

It turns out that, at some point, NixOS stopped putting `/run/opengl-driver/lib` in the `LD_LIBRARY_PATH` by default.  You can fix this by putting this in your configuration.nix file:
```
hardware.opengl.setLdLibraryPath = true;
```

**Comment by locallycompact** [comment]
I don't seem to be getting this error anymore. Closing
