### ISSUE TITLE
genvulkan runtime error on windows ( my opinion )

### ISSUE THREAD

**Issue by ubuntunux** [achirkin/vulkan#39]
https://github.com/achirkin/vulkan/issues/21

I Just recommend to fix your code like this.

Define.hs 53 line

&& (c == "#define VK_MAKE_VERSION(major, minor, patch) \\\n    (((major) << 22) | ((minor) << 12) | (patch))" || c == "#define VK_MAKE_VERSION(major, minor, patch) \\\r\n    (((major) << 22) | ((minor) << 12) | (patch))")

It works on any os.

**Comment by achirkin** [comment]
Hmm, I forgot about this issue. It's kind of low-priority, because you normally don't need to use genvulkan unless you want to update `vk.xml` version (just use the source code of vulkan-api that was generated on linux and saved in the repo).

Does the whole generation process work well then? And does `vulkan-triangles` work with the generated source? If everything works well, could you please make a corresponding PR?

**Comment by ubuntunux** [comment]
Yes, I have tested whole generation process on windows and  ubuntu. It work well all of the examples. what is the PR?

**Comment by achirkin** [comment]
PR stands for Pull Request. Thanks, I am merging your change!
